### ISSUE TITLE
improve the UI of "our happy clients say" section of the website

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#11]
-Visit the website for more details
https://shrutimishra-2002.github.io/The-Mandarin-Oriental/?

**Comment by The-Yash-Anand** [comment]
Hey, I'll love to contribute to this issue, looking forward to working. Would appreciate it if you will assign me.

**Comment by mufida1018** [comment]
I want to contribute to this under hacktober

**Comment by cyberciph3r** [comment]
I would like to improve the look of this section. I want to work on this issue.

**Comment by Divyanshi2408** [comment]
Hey @ShrutiMishra-2002  I would like to contribute to this issue for Hacktoberfest 2022 Could you please assign me this issue ?

**Comment by ManishMadan2882** [comment]
Hey, I can work to imporove the UI and fonts of this repo for Hacktober 22 using TailwindCSS

**Comment by tahseenzahra** [comment]
Hello, I would like to contribute to your code can you please add me as a collaborator?

**Comment by adityasandy313** [comment]
hey, @ShrutiMishra-2002 please assign this issue to me.

**Comment by my1243** [comment]
Hey 👋 
I would like to contribute in this issue. Can u please assign it to me. I will fix it with the help of tailwind css.

**Comment by Akash-moon** [comment]
Hllo @ShrutiMishra-2002 I want to contribute my efforts on this problem.
Please assign it to me under Hacktoberfest22.

**Comment by sidmadke** [comment]
@ShrutiMishra-2002 Hiii! I can enhance it to next level💯.Can you please assign me this task.

**Comment by ShrutiMishra-2002** [comment]
@sidmadke @cyberciph3r goahead

**Comment by sidmadke** [comment]
@ShrutiMishra-2002 Made PR for task #59 
Please check it out😇
