### ISSUE TITLE
Login & SignUp Functionality

### ISSUE THREAD

**Issue by ZaidKhan2002** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#12]
It's better that we store the user's information. Firebase is easy to use and simple to implement. Can I go ahead with it under hacktober tag.

**Comment by cyberciph3r** [comment]
I would like to add the "login with google"  and "login with Facebook" features to the website. I would like to be assigned to this issue.

**Comment by coder-chahal** [comment]
please assign to me

**Comment by ShrutiMishra-2002** [comment]
Yes go ahead @ZaidKhan2002 and connect with the firebase

**Comment by sandesh10000** [comment]
hey @ShrutiMishra-2002 can I work on this issue ? i will use MySQL and node.js

**Comment by ZaidKhan2002** [comment]
Hey @ShrutiMishra-2002 I made a PR #38  regarding this could you review that
