### ISSUE TITLE
Headings are not clearly visible

### ISSUE THREAD

**Issue by VasuDevrani** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#2]
The headers of the 'Rooms' and 'testimonial' sections are not clear

<img width="493" alt="image" src="https://user-images.githubusercontent.com/101383635/193338707-055b4454-1d07-4ee6-8c4a-12bfb16e8a8d.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/101383635/193338751-7cb45ba9-3afd-4a30-bf85-a1e2901362b5.png">

# I would like to work on this issue. Please assign it to me.

**Comment by Elvis020** [comment]
What resolution are you suggesting? sorry but I think the issue is not clear enough.
The Headers are not clear in what sense, I can see that it's difficult to read, with their respective backgrounds.

What resolution are you suggesting

**Comment by Aftabalam162** [comment]
Hello, I would like to contribute to this issue. Please let me know what should I edit and what shouldn't like can I add a div to the headers or I can just change the font-size.

**Comment by jyotika6221** [comment]
Please assign me with this task.

**Comment by cyberciph3r** [comment]
@ShrutiMishra-2002  Worked on this issue. Made a PR #61

**Comment by Rajnish-bhagat** [comment]
@mdnazisharman2803 , I can work on it. Could you assign it to me?

**Comment by cyberciph3r** [comment]
@mdnazisharman2803 hey,  I have already worked on this issue and the PR has been merged. Are there any further changes that need to be done to this issue?
