### ISSUE TITLE
Modify the navigation section 

### ISSUE THREAD

**Issue by subhajitroycode** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#21]
Hi there, I want to improve and modify the navigation section for the website. 

When we click the menu and it appears from the right I think it's not necessary for the desktop view so please assign me this issue 🙏 also this is my first hacktoberfest.

**Comment by ShrutiMishra-2002** [comment]
Please attach the screenshot for what you want to change @subhajitroycode

**Comment by ianujvarshney** [comment]
I can fix this issue. @subhajitroycode could you assisgn me please ☺️?

**Comment by subhajitroycode** [comment]
Hi @ShrutiMishra-2002 

Sorry I've been a bit late but here is what I wanted to change; you can watch this [video](https://user-images.githubusercontent.com/72935263/193823660-0a2de64c-6ea7-4abe-afb5-219e8ad99320.mp4)

So if you assign me this task then I can make a pull request and it'd be great.

**Comment by subhajitroycode** [comment]
Thank you so much for this 😊
