### ISSUE TITLE
Move contribution guiidelines from README.md to CONTRIBUTION.md

### ISSUE THREAD

**Issue by slim-codes** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#24]
Hello there!
The contribution guidelines should be in the contribution.md file
The README on the other hand should basically showcase the project and point the reader to the contributing.md instructions

If you approve, I'd like to implement these modifications
Thank you

**Comment by ShrutiMishra-2002** [comment]
It is already present in the contributing.md file.
