### ISSUE TITLE
Links in footer section should have a hover effect

### ISSUE THREAD

**Issue by slim-codes** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#25]
![Screenshot from 2022-10-02 15-01-23](https://user-images.githubusercontent.com/72257135/193458067-e4a9e4e2-1ddc-482e-b8e1-f780e02272e3.png)
The links under the **Useful Links** section should have a hover effect (they should have an underline animation) just to improve the UX

**Comment by Esha-01** [comment]
@slim-codes assign this to me . I can do it.

**Comment by ShrutiMishra-2002** [comment]
Please make a valid pr! @slim-codes @Esha-01
