### ISSUE TITLE
Modifying the Navigation Section of the website

### ISSUE THREAD

**Issue by abhishekrd** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#32]
In the current website, the navigation is of hamburger menu type which is more likely to be used in mobile devices. In desktop view, The overall user experience and UI will look great if the navigation section is horizontal. I can do it very nicely. @ShrutiMishra-2002  can you please assign it to me?
![Screenshot 2022-10-04 010629](https://user-images.githubusercontent.com/88556842/193663699-ed85bb8b-64e9-44f2-9e5c-6a3feb1025a7.png)
![Screenshot 2022-10-04 010652](https://user-images.githubusercontent.com/88556842/193663722-9834eb28-a083-475e-a926-b2cfa8c75416.png)

**Comment by abhishekrd** [comment]
@ShrutiMishra-2002 screenshot is added already.

**Comment by ShrutiMishra-2002** [comment]
@abhishekrd add screenshot for the changes you made !

**Comment by ShrutiMishra-2002** [comment]
@abhishekrd some one else is already working on it!

**Comment by abhishekrd** [comment]
Ok
