### ISSUE TITLE
Improving syling

### ISSUE THREAD

**Issue by sumitkr2000** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#35]
Hey @ShrutiMishra-2002 I want to add some styling on your beautiful website. Can you assign me this issue so that I can work on it?

**Comment by ShrutiMishra-2002** [comment]
@sumitkr2000 please add a screenshot

**Comment by sumitkr2000** [comment]
@ShrutiMishra-2002 I havent added it yet but if u will assign ill add
