### ISSUE TITLE
Adding Scroll up button functionality on Home page

### ISSUE THREAD

**Issue by rushikesh1799** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#41]
Hi @ShrutiMishra-2002, I am new to the open source world and would love to contribute to THE MANDARIN ORIENTAL.

THE MANDARIN ORIENTAL looks clean and fantastic. One thing I would like to add is the scroll-up button functionality to the home page. Once anyone clicks on the scroll-up button it will take the user to the top of our website.

Can you please assign this to me? Thanks.

**Comment by ShrutiMishra-2002** [comment]
Please make a valid pr

**Comment by rushikesh1799** [comment]
Yes sure, could you please assign this to me and add hacktoberfest and hacktoberfest-accepted tags.

**Comment by coder-chahal** [comment]
Hii ma'am, can i work it too ?

**Comment by rushikesh1799** [comment]
@ShrutiMishra-2002 I have already submitted PR, can you please review the PR and merge it with suitable labels? Please let me know if there are any issues.
