### ISSUE TITLE
Add navigation on the "BOOK NOW" button

### ISSUE THREAD

**Issue by Lo-rraine** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#46]
Hi there,

I noticed that before you get to the room's section there is a form for booking. I would like to make the following changes:
   1. Remove this booking form
![image](https://user-images.githubusercontent.com/65586580/194378468-b865a3ba-ca15-4391-a41f-fe0f90ea15b9.png)

   2. Add Navigation to a new Bookings Page when the "BOOK NOW" button is clicked https://res.craft.do/user/full/d78e1482-5fe5-b1b0-657a-0f4bc4f2f024/doc/78c16db3-d109-4560-8f9c-8595f9544b25/b802e6fe-8221-458e-9553-2a79fa2c0a58
   3. Add the Book now form to the Bookings page that I'll and some styling work so that the page matches the rest of the website

**Comment by aryan2909** [comment]
Hey pls assign me this issue
