### ISSUE TITLE
hi, adding a favicon to the website,can i do this under hackotoberfest 2022

### ISSUE THREAD

**Issue by Janhvi52** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#55]

**Comment by ShrutiMishra-2002** [comment]
please make a valid pr @Janhvi52

**Comment by Janhvi52** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/97719669/194801150-d0512515-44af-400a-b4cf-16e5118ebc25.png)

Hi shruti,
I've done a valid pr already,its showing no conflicts and able to merge with your branch,can you refer it once and merge the same
Thankyou!
@ShrutiMishra-2002
