### ISSUE TITLE
Add Hover Effects on Buttons

### ISSUE THREAD

**Issue by akanshaaa19** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#85]
If the buttons changes slight colors when hovered, they would look even better

**Comment by akanshaaa19** [comment]
Please assign

**Comment by narendradeo7** [comment]
can i work upon it , as i have good experience with css smooth transition and color schema as per page

**Comment by Vaibhavraj-nath-chauhan** [comment]
Can you please assign this issue to me
