### ISSUE TITLE
create custom scrollber

### ISSUE THREAD

**Issue by SayantanmPaul** [ShrutiMishra-2002/hacktoberfest22_hotel_mandarin_oriental#96]
the webpage has only the custom scrollbar

Here is the element I want to improve color and the design can be changeable :
![scrollbar](https://user-images.githubusercontent.com/103353878/197836353-4710793b-0235-4760-8916-9128c0308e54.PNG)

Kindly the issue me if it's worth the changes to the design of the page 
Thank you,
**Sayantan**

**Comment by SayantanStackflow** [comment]
Hi, have you checked the issue I have raised? @ShrutiMishra-2002
